# Generated by Django 4.2.4 on 2023-10-07 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=500)),
                ('lastName', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(blank=True, max_length=250)),
                ('cvFile', models.FileField(upload_to='cv-files')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('number', models.CharField(blank=True, max_length=250)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('message', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrepreuneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('companyName', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('website', models.CharField(max_length=500)),
                ('fieldOfProfessional', models.CharField(max_length=500)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=500)),
                ('lastName', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birthDate', models.DateField(blank=True)),
                ('countryOfResidence', models.CharField(blank=True, max_length=500)),
                ('provinceOfResidence', models.CharField(blank=True, max_length=500)),
                ('companyName', models.CharField(blank=True, max_length=500)),
                ('interestes', models.CharField(blank=True, max_length=500)),
                ('preferredAreas', models.CharField(blank=True, max_length=500)),
                ('howDidYouKnowUs', models.CharField(blank=True, max_length=500)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=500)),
                ('lastName', models.CharField(blank=True, max_length=500)),
                ('birthDate', models.DateField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('countryOfResidence', models.CharField(blank=True, max_length=500)),
                ('provinceOfResidence', models.CharField(blank=True, max_length=500)),
                ('companyName', models.CharField(blank=True, max_length=500)),
                ('investmentCeiling', models.CharField(blank=True, max_length=500)),
                ('howDidYouKnowUs', models.CharField(blank=True, max_length=500)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StartUpsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=300)),
                ('lastName', models.CharField(blank=True, max_length=300)),
                ('birthDate', models.DateField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('countryOfResidence', models.CharField(blank=True, max_length=300)),
                ('provinceOfResidence', models.CharField(blank=True, max_length=300)),
                ('type', models.CharField(blank=True, max_length=300)),
                ('ideaExplanation', models.CharField(blank=True, max_length=300)),
                ('getToKnowUs', models.CharField(blank=True, max_length=300)),
                ('pitchDeckFile', models.FileField(blank=True, null=True, upload_to='pitchdeckfile')),
                ('businessPlanFile', models.FileField(blank=True, null=True, upload_to='businessPlan')),
                ('productName', models.CharField(blank=True, max_length=500)),
                ('siteAddress', models.CharField(blank=True, max_length=500)),
                ('customerProblem', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('productLevel', models.CharField(blank=True, max_length=200)),
                ('scalable', models.TextField(blank=True)),
                ('monetizationOfYourPlan', models.TextField(blank=True)),
                ('structureOfYourSales', models.TextField(blank=True)),
                ('financialModelFile', models.FileField(blank=True, null=True, upload_to='financialModelFile')),
                ('cooperatedWithInvestors', models.TextField(blank=True)),
                ('financialFile', models.FileField(blank=True, null=True, upload_to='financialFile')),
                ('customerCharacteristic', models.TextField(blank=True)),
                ('currentCustomers', models.TextField(blank=True)),
                ('estimatedMarketSize', models.TextField(blank=True)),
                ('totalTamSamSom', models.TextField(blank=True)),
                ('startupRevenue', models.TextField(blank=True)),
                ('monthlyIncome', models.TextField(blank=True)),
                ('currentInterestRate', models.TextField(blank=True)),
                ('currentRaisedFunding', models.TextField(blank=True)),
                ('neededCapital', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
