# Generated by Django 4.2.4 on 2023-09-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupsform',
            name='businessPlanFile',
            field=models.FileField(blank=True, null=True, upload_to='businessPlan'),
        ),
        migrations.AlterField(
            model_name='startupsform',
            name='financialFile',
            field=models.FileField(blank=True, null=True, upload_to='financialFile'),
        ),
        migrations.AlterField(
            model_name='startupsform',
            name='financialModelFile',
            field=models.FileField(blank=True, null=True, upload_to='financialModelFile'),
        ),
        migrations.AlterField(
            model_name='startupsform',
            name='pitchDeckFile',
            field=models.FileField(blank=True, null=True, upload_to='pitchdeckfile'),
        ),
    ]
