# Generated by Django 4.2.4 on 2023-09-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreuneur',
            name='website',
            field=models.CharField(max_length=500),
        ),
    ]
