# Generated by Django 4.2.4 on 2023-10-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investorregistration',
            old_name='interestes',
            new_name='interests',
        ),
    ]
