# Generated by Django 4.2.4 on 2023-11-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_rename_interestes_investorregistration_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='cvFile',
            field=models.FileField(blank=True, null=True, upload_to='cv-files'),
        ),
    ]
