# Generated by Django 4.2.4 on 2023-10-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_vacation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Decline')], default=1),
        ),
    ]
