# Generated by Django 4.2.4 on 2023-09-11 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_entrepreuneur_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investorregistration',
            old_name='investmentCeiling',
            new_name='interestes',
        ),
    ]
