# Generated by Django 4.2.4 on 2023-10-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_vacation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacation',
            options={'permissions': [('can_create_mymodel', 'Can create mymodel'), ('can_view_mymodel', 'Can view mymodel'), ('can_edit_mymodel', 'Can edit mymodel'), ('can_delete_mymodel', 'Can delete mymodel')]},
        ),
    ]
