# Generated by Django 4.2.4 on 2023-09-11 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_rename_investmentceiling_investorregistration_interestes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=500)),
                ('lastName', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(blank=True, max_length=250)),
                ('cvFile', models.FileField(upload_to='cv-files')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='entrepreuneur',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrepreuneur',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
