# Generated by Django 4.2.4 on 2023-12-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_handicraft_landagene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landagene',
            name='company_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
