# Generated by Django 4.2.4 on 2024-02-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_landagene_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkWithUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_position', models.CharField(max_length=250)),
                ('type_of_contract', models.CharField(max_length=250)),
                ('your_first_name', models.CharField(max_length=250)),
                ('your_last_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('your_field_of_study', models.CharField(max_length=250)),
                ('your_subfield', models.CharField(max_length=250)),
                ('your_skills', models.CharField(max_length=250)),
                ('number_of_credits_passed', models.CharField(max_length=250)),
                ('your_resume', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
