# Generated by Django 4.2.4 on 2024-02-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_workwithus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workwithus',
            old_name='number_of_credits_passed',
            new_name='your_national_id_number',
        ),
        migrations.RemoveField(
            model_name='workwithus',
            name='your_resume',
        ),
        migrations.RemoveField(
            model_name='workwithus',
            name='your_skills',
        ),
    ]
