# Generated by Django 4.2.4 on 2024-03-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_applyjob_createdat_alter_applyjob_email_and_more'),
        ('forms', '0008_remove_workwithus_your_national_id_number_and_more'),
    ]

    operations = [
    ]
