# Generated by Django 4.2.4 on 2024-03-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_merge_20240313_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workwithus',
            name='type_of_contract',
        ),
        migrations.RemoveField(
            model_name='workwithus',
            name='your_field_of_study',
        ),
        migrations.RemoveField(
            model_name='workwithus',
            name='your_position',
        ),
        migrations.RemoveField(
            model_name='workwithus',
            name='your_subfield',
        ),
        migrations.AddField(
            model_name='investorregistration',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=250, verbose_name='شماره موبایل'),
        ),
    ]
