# Generated by Django 4.2.4 on 2024-03-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_remove_workwithus_type_of_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorregistration',
            name='birthDate',
            field=models.DateField(blank=True, null=True, verbose_name='ایمیل'),
        ),
    ]
