# Generated by Django 4.2.4 on 2024-03-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_alter_investorregistration_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreuneur',
            name='first_name',
            field=models.CharField(default=' ', max_length=500, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrepreuneur',
            name='last_name',
            field=models.CharField(default='some test name', max_length=500, verbose_name='نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partnermembership',
            name='birthDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
    ]
