# Generated by Django 4.2.4 on 2024-03-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_partnermembership_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='workwithus',
            name='type_of_contract',
            field=models.CharField(default='random', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workwithus',
            name='your_field_of_study',
            field=models.CharField(default='agian random', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workwithus',
            name='your_position',
            field=models.CharField(default='random', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workwithus',
            name='your_subfield',
            field=models.CharField(default='random', max_length=250),
            preserve_default=False,
        ),
    ]
