# Generated by Django 4.2.4 on 2024-03-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_workwithus_type_of_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handicraft',
            name='phone_number',
            field=models.CharField(blank=True, max_length=250, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='entrepreuneur',
            name='first_name',
            field=models.CharField(max_length=500, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='entrepreuneur',
            name='last_name',
            field=models.CharField(max_length=500, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='investorregistration',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='partnermembership',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='شماره موبایل'),
        ),
    ]
