# Generated by Django 4.2.4 on 2023-10-07 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emails',
            field=models.ManyToManyField(null=True, related_name='user_emails', to=settings.AUTH_USER_MODEL),
        ),
    ]
