# Generated by Django 4.2.4 on 2023-10-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_alter_user_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='group',
            field=models.ManyToManyField(to='auth.group', verbose_name='group role'),
        ),
    ]
