# Generated by Django 4.2.4 on 2024-01-04 07:48

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(upload_to='events/banner/images', verbose_name='بنر'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(related_name='event_speakers', to=settings.AUTH_USER_MODEL, verbose_name='سخنگو ها'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='به روز شده در'),
        ),
        migrations.AlterField(
            model_name='event',
            name='video',
            field=models.FileField(null=True, upload_to='events/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='ویدئو'),
        ),
        migrations.AlterField(
            model_name='eventform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در'),
        ),
        migrations.AlterField(
            model_name='eventform',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='eventform',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.event', verbose_name='رویداد'),
        ),
        migrations.AlterField(
            model_name='eventform',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='eventform',
            name='reserved_count',
            field=models.IntegerField(default=1, verbose_name='تعداد رزرو'),
        ),
        migrations.AlterField(
            model_name='eventform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='به روز شده در'),
        ),
        migrations.AlterField(
            model_name='images',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='event.event', verbose_name='رویداد'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='events/images', verbose_name='تصویر'),
        ),
    ]
