# Generated by Django 4.2.4 on 2023-10-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='VACATION_STATUS',
            field=models.IntegerField(choices=[(1, 'illness'), (2, 'entitlement')], default=1),
        ),
    ]
