# Generated by Django 4.2.4 on 2023-10-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_vacation_vacation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacation',
            options={'ordering': ('-created_at',), 'permissions': [('can_create_vacation', 'Can create vacation'), ('can_view_vacation', 'Can view vacation'), ('can_edit_vacation', 'Can edit vacation'), ('can_delete_vacation', 'Can delete vacation'), ('can_get_all_vacation', 'Can Get All vacation')]},
        ),
        migrations.RenameField(
            model_name='vacation',
            old_name='VACATION_STATUS',
            new_name='vacation_status',
        ),
    ]
