# Generated by Django 4.2.4 on 2023-12-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.SlugField(max_length=150, unique=True, verbose_name='نام کاربری')),
                ('first_name', models.CharField(max_length=150, verbose_name='نام')),
                ('last_name', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=250, verbose_name='ایمیل')),
                ('linkedin', models.URLField(blank=True, null=True, unique=True, verbose_name='لینکدین')),
                ('whatsapp', models.URLField(blank=True, null=True, unique=True, verbose_name='واتساپ')),
                ('instagram', models.URLField(blank=True, null=True, unique=True, verbose_name='اینستاگرام')),
                ('telegram', models.URLField(blank=True, null=True, unique=True, verbose_name='تلگرام')),
                ('websites', models.JSONField(blank=True, null=True, verbose_name='سایت ها')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='profile/images', verbose_name='عکس پروفایل')),
                ('qrcode_image', models.ImageField(blank=True, default='', upload_to='qrcodes/')),
            ],
        ),
    ]
