# Generated by Django 4.2.4 on 2023-12-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_website_remove_profile_websites_profile_websites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='websites',
            field=models.ManyToManyField(blank=True, to='user_profile.website'),
        ),
    ]
