# Generated by Django 4.2.4 on 2023-12-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_profile_websites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(default='', max_length=250, verbose_name='عنوان شغلی'),
        ),
    ]
