# Generated by Django 4.2.4 on 2024-01-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_website_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='websites',
            field=models.ManyToManyField(blank=True, to='user_profile.website', verbose_name='سایت ها'),
        ),
    ]
